"""Update link table to remove unique constraint

Revision ID: 56e31b57b441
Revises: dc82368c6b76
Create Date: 2022-08-28 23:30:20.829590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56e31b57b441'
down_revision = 'dc82368c6b76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('link_username_key', 'link', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('link_username_key', 'link', ['username'])
    # ### end Alembic commands ###
