"""Update link table

Revision ID: dc82368c6b76
Revises: 417fc14b5690
Create Date: 2022-08-28 19:21:10.475016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc82368c6b76'
down_revision = '417fc14b5690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('visible', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'visible')
    # ### end Alembic commands ###
