"""Add image url field to user table

Revision ID: ed91e676df7c
Revises: f080a0793c40
Create Date: 2022-09-05 10:35:03.366483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed91e676df7c'
down_revision = 'f080a0793c40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_url', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image_url')
    # ### end Alembic commands ###
