"""Add cascade deletion to link table

Revision ID: f080a0793c40
Revises: 56e31b57b441
Create Date: 2022-09-01 18:08:35.962755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f080a0793c40'
down_revision = '56e31b57b441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('link_username_fkey', 'link', type_='foreignkey')
    op.create_foreign_key(None, 'link', 'user', ['username'], ['username'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'link', type_='foreignkey')
    op.create_foreign_key('link_username_fkey', 'link', 'user', ['username'], ['username'])
    # ### end Alembic commands ###
